# Generated by Django 4.2.5 on 2023-09-06 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50, verbose_name='Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_fio', models.CharField(max_length=50, verbose_name='Teacher Fio')),
            ],
        ),
        migrations.AddField(
            model_name='lessons',
            name='lesson_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Lesson date'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='lesson_title',
            field=models.CharField(max_length=100, verbose_name='Lesson title'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='lesson_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='themes.subjects', verbose_name='Subject ID'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='lesson_teacher',
            field=models.ManyToManyField(null=True, to='themes.teachers', verbose_name='Teachers ID'),
        ),
    ]
