# Generated by Django 4.2.5 on 2023-09-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.PositiveIntegerField(default='score'),
            preserve_default=False,
        ),
    ]
