# Generated by Django 4.2.5 on 2023-09-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Countries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Country name")),
                ("population", models.IntegerField(verbose_name="Population")),
                ("area", models.FloatField(verbose_name="Area")),
                ("density", models.FloatField(verbose_name="Density")),
            ],
            options={
                "db_table": "countries",
            },
        ),
    ]
