# Generated by Django 4.2.5 on 2023-09-18 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Themes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "themes",
            },
        ),
        migrations.CreateModel(
            name="Plans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan", models.CharField(max_length=255)),
                (
                    "plan_theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_site.themes",
                    ),
                ),
            ],
            options={
                "db_table": "plans",
            },
        ),
    ]
