# Generated by Django 4.2.5 on 2023-09-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Capitals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contry_uz", models.CharField(max_length=255)),
                ("capital_uz", models.CharField(max_length=255)),
                ("contry_en", models.CharField(max_length=255)),
                ("capital_en", models.CharField(max_length=255)),
                ("contry_ru", models.CharField(max_length=255)),
                ("capital_ru", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "capitals",
            },
        ),
    ]
