# Generated by Django 4.2.3 on 2023-09-16 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_capitals", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="capitals",
            old_name="contry_en",
            new_name="country_en",
        ),
        migrations.RenameField(
            model_name="capitals",
            old_name="contry_ru",
            new_name="country_ru",
        ),
        migrations.RenameField(
            model_name="capitals",
            old_name="contry_uz",
            new_name="country_uz",
        ),
    ]
